name: RTO and Raster
description: The design pattern and framework for websites
meta_description: "The base resource about RTO and Raster"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://draganescu.github.io/'
author:         'Andrei Draganescu'
